### ISSUE TITLE
Unusual interactions with Fast Leaf Decay (Mod version 0.3.507)

### ISSUE THREAD

**Issue by xsneakyxsimx** [pahimar/Equivalent-Exchange-3#1008]
When used with Fast Leaf Decay (1.0), it seems to remove EMC values and makes vanilla dyes (except for Lapis Lazuli), dyed variants of wool, hardened clay, glass (block and panes), cobblestone walls, and certain tools, as well as items from Progressive Automation unable to be learned.  May have altered more but those were the items I noted as being different when the mod was active, and were restored when it was deactivated.  Also making a similar post onto Fast Leaf Decay's Issues page.

**Comment by Olafski** [comment]
Hi, I'm the developer for Fast Leaf Decay. Since I can't think of any way my mod interacts with EE3, I'm just reporting in here to show support. If I can help Pahimar in any way to figure this out, or vice versa, I'd be happy to.

As I stated on the issue you created on my mod page, I currently have no idea how our two mods interact. My mod only modifies a few blocks and of those blocks it interacts with an event listener. The report you put here deals with a lot of blocks and items (dyes have no block equivalent as far as I know). Again, if I can help with the debugging please let me know.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
