### ISSUE TITLE
Aludel Not "Smelting" Items

### ISSUE THREAD

**Issue by JREAPER99** [pahimar/Equivalent-Exchange-3#1024]
I'm playing a mod pack with EE3 and as I began playing on a server I wanted to start EE3 because I figured it would be a good change from EE2 or ProjectE. As I began playing with it I realized I needed to maek certain blocks to make other things and etc. When I got to making a Tome of Alchemical Knowledge I put the book and minium dust and coal into the Aludel and nothing happened. I then tried to make Ash Infused Stone and the same thing happened. I then went to a single player world just to make sure it wasn't the server stopping me and the same thing happened there. I read the wiki on how everything works and I can't figure out what is wrong.

**Comment by WolfAmaril** [comment]
Did you have a glass bell on top of the Aludell base, or just the Aludell base?

**Comment by JREAPER99** [comment]
I had the glass bell on top of the base as well. In the GUI I placed the items in and nothing happened.

**Comment by WolfAmaril** [comment]
And you had fuel in the bottom?

**Comment by JREAPER99** [comment]
Yes

**Comment by JREAPER99** [comment]
![2015-12-05_21 21 27](https://cloud.githubusercontent.com/assets/16171498/11611335/2729488a-9b96-11e5-83f9-191c482ce921.png)
![2015-12-05_21 21 03](https://cloud.githubusercontent.com/assets/16171498/11611336/292cfece-9b96-11e5-95e3-05659cacaa53.png)

**Comment by WolfAmaril** [comment]
OK, I am officially stumped. My first instinct is to say that someone modified the recipies with mine/modtweaker but unless they wrote their own EE3 handlers for either of those I can't see how. I guess at this point the questions I have are what modpack is this and what version of EE3 because quite honestly the backgrounds for the Aludel GUI look really, really old and it's possible that the version of EE3 included just doesn't have aludel functionality yet.

**Comment by iTitus** [comment]
Could you please verify your recipes with EE3's NEI recipe handler, maybe the recipes are wrong.

**Comment by pahimar** [comment]
Please post a complete FML log so that we can what version of EE3 you are running, and if there are any errors/etc.
