### ISSUE TITLE
Shift click issues with Transmutation Tablet in build 519

### ISSUE THREAD

**Issue by cylek56** [pahimar/Equivalent-Exchange-3#1054]
Hello Pahimar,

Just want to report bugs:
(Win 10/ MC 1.7.10/ Java 1.8.091/ Forge 10.13.4.1614)

1-Glyph twinkles on each size (1x1, 3x3, 5x5)
2-Aeternalis blocks turn to Alchemical blocks when shift clicking the transmutation table 
Same for pufferfish which turns to raw fish

Hope to help you a little
Respectfully

**Comment by pahimar** [comment]
Twinkles?

**Comment by cylek56** [comment]
![glyph](https://cloud.githubusercontent.com/assets/16599003/15456155/40b9f8d8-2068-11e6-9386-4fdb0e017194.gif)

Easier to show what's going wrong

**Comment by pahimar** [comment]
That's very odd - it should be a smooth glow effect. Hrm

**Comment by tterrag1098** [comment]
Came from twitter - I know I'm looking at the wrong part of this issue, but you might consider using a sine wave here instead of...uh...this? https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/client/util/RenderUtils.java#L85

`Math.sin(world.getTotalWorldTime() / 100f)`

Will be guaranteed smooth and based on world time so it stops when the game pauses

**Comment by pahimar** [comment]
Yeah the render stuff was always fugly and wasn't going to be ported to 1.9 :) Good recommendation though!

**Comment by tterrag1098** [comment]
Ah...small mistake...obviously sin returns negative values, you'd need to interpolate on 0..1 ( `(sin(...) + 1) / 2f` )

**Comment by tterrag1098** [comment]
Looked into TSIS, your bug is simpler than you may think.

https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/inventory/ContainerTransmutationTablet.java#L345

`ItemStack#clone()` exists for a reason ;)

**Comment by Texasjake95** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/inventory/ContainerTransmutationTablet.java#L376
Shouldn't this also have the Item damage as well or I am miss reading something?

**Comment by pahimar** [comment]
I caught that one. Thing is when you clone it you get weird other behaviour (a item dupe exploit in fact).

**Comment by pahimar** [comment]
Clone/pass in the meta. The dupe exploit is there.

**Comment by pahimar** [comment]
Pushed the piece that fixes the meta (https://github.com/pahimar/Equivalent-Exchange-3/commit/4fac58d4221d642cac6141ba73fea69be12bb721) however the dupe exploit still exists. That's the thing I'm more concerned about.

**Comment by MaPePeR** [comment]
@pahimar [this line](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/inventory/ContainerTransmutationTablet.java#L375) drops the damage value information from `itemStack`.

**Comment by pahimar** [comment]
@MaPePeR a good catch, but the dupe exploit still exists even with that change

**Comment by MaPePeR** [comment]
@Pahimar what is the dupe exploit then? Can you elaborate?

**Comment by pahimar** [comment]
Steps to reproduce;

1. Teach yourself an Aeternalis Fuel Block
2. In a new Transmutation Tablet, add a full stack of Aeternalis Fuel Blocks to the input section
3. Shift click out a full stack of Aeternalis Fuel Blocks from the output section

**Comment by pahimar** [comment]
1) Re: twinkles - commit https://github.com/pahimar/Equivalent-Exchange-3/commit/43a384a2e6d3d3e9cf73397bd77e4a8b52db38cf should fix that issue for you
2) This is not a shift click issue, but rather an issue with how the transmutation tablet consumes items for EMC in order to do the transmutation (see bug #1057)

With that said, going to close this issue and track the issue with the trans tablet in #1057
