### ISSUE TITLE
data/ee3/blacklist/knowledge-blacklist.json not working?

### ISSUE THREAD

**Issue by LemADEC** [pahimar/Equivalent-Exchange-3#1071]
As found in FTB Inventions, the data/ee3/blacklist/knowledge-blacklist.json has an entry for oreIron:
![image](https://cloud.githubusercontent.com/assets/4776032/15803151/dbbd8b58-2acf-11e6-94e9-461c25ec9539.png)

According to NEI, minecraft iron ore is registered into the ore dictionnary as oreIron:
![image](https://cloud.githubusercontent.com/assets/4776032/15803149/c5d92d06-2acf-11e6-9ecd-b4b664a4d11f.png)

Yes, players are able to research iron ore.
Is it a wip feature?

**Comment by pahimar** [comment]
This is a bug in the version of EE3 in FTB Inventions, it's fixed in the latest version of EE3 (v0.3.0.547). At this point basically just waiting on tfox83 to update the mod in the pack.

**Comment by LemADEC** [comment]
Will the players automatically unlearn those items or do we need to do it manually?

**Comment by pahimar** [comment]
It will need to be done manually.

**Comment by LemADEC** [comment]
the bug applies to the whole blacklist or just oreDictionnary names?

**Comment by pahimar** [comment]
Commits that fixed it:
- https://github.com/pahimar/Equivalent-Exchange-3/commit/7ac01e09a6b37561c6bd2fc34fe1768f682cf0cd
- https://github.com/pahimar/Equivalent-Exchange-3/commit/f119a3a907070793be1e7b142be76706c32aa847
- https://github.com/pahimar/Equivalent-Exchange-3/commit/63ac5b0819c15d372eeb7082a2935a001d01c494

The problem was that the code wasn't checking if the itemstack that is being checked was a member of an oredictionary entry that was blacklisted (it was only checking the itemstack specifically). It's fixed. Waiting on FTB.
