### ISSUE TITLE
Item Energy Inconsistencies

### ISSUE THREAD

**Issue by blueMagician** [pahimar/Equivalent-Exchange-3#1087]
I don't know if this has already been addressed, but I noticed 2 big inconsistencies that can be easily abused.
1. A vanilla Bucket has an energy of 1 while iron has an energy rating of 256.
2. I don't know if you deal with mod energy values, but Thaumcraft nuggets (specifically gold nuggets) have an exchange value equal to the ingots.

**Comment by escman1999** [comment]
shouldn't the empty buckets have an emc value of 768?

**Comment by x3n0ph0b3** [comment]
I had to fix mine manually. It's a known issue with buckets, specifically.

**Comment by blueMagician** [comment]
Normally, that would make sense. I am using version 525, so I don't know if
that's been fixed, I just wanted to bring it to everyone's attention since
that is... quite a problem, especially with something like Tinker's
construct which can melt down said buckets.

**Comment by FMC312** [comment]
I'm using 547, bucket is 1 EMC. so yeah, just dropping some information by.

**Comment by pahimar** [comment]
This is not a known issue at least to me. I need to see your
fml-client-latest log file and your energy values json. You also need to be
on ee3 547.

**Comment by pterolatypus** [comment]
Seems it's caused by interaction with another mod. Testing in a clean instance gives the expected behvaiour:
http://pastebin.com/0tu2EfFQ

Whereas testing in the FTB Infinity Evolved pack gives the following:
http://pastebin.com/fK4Cq03M

Not sure what recipe that is that's confusing it. Possibly the TE Fluid Transposer? Strange, as you can see at that stage water_bucket doesn't even have a value of its own so it shouldn't be trying to calculate it.

**Comment by pahimar** [comment]
This is a mod interaction issue. A mod is registering recipes with EE3 such that EE3 computes that a bucket's lowest value should be 1. Earlier in the logs you would find what mod, at what point, adds the recipe that resolves to a value of 1 (if you see that EE3 is adding a recipe, thats EE3 adding the recipes registered in the vanilla recipe handlers).
