### ISSUE TITLE
Thermal Foundation Emc Bug

### ISSUE THREAD

**Issue by mxnmnm** [pahimar/Equivalent-Exchange-3#1105]
Metals such as electrum have emc values like 1.078 instead of 1,078.  This happens to a lot of other thermal foundation metals.

**Comment by MercuriusXeno** [comment]
Versions of the mod you're using? Versions of MC you're using? Versions of Thermal being used? Liquid metal? Solid metal? Be advised, afaik, nobody is backporting fixes to 1.7.10 unless you ask super nicely and even then, you may end up baking your own or waiting for someone nice. It's possibly an error to do with liquid metal EMC since it's per mB - have the values been incorrectly swapped, etc?

**Comment by pahimar** [comment]
Thermal Foundation adds their own values via their EE3 mod integration. @mxnmnm  please report issues with their values to them, and they can escalate here in the event that they believe there is an issue with how values are calculated.

**Comment by MexRex** [comment]
Dear friend! 

Take a look at that adorable  stuff,  I'm  just amazed! It is so sweet)) Here, check it out <http://important.strategyedu.com/e8fvi>

All best, SHoCKYCooKIE
