### ISSUE TITLE
Botania/Bauble Issue

### ISSUE THREAD

**Issue by Gengi0927** [pahimar/Equivalent-Exchange-3#1116]
Hello, I am having problems with Botania, I have downloaded both of the required mods, however Minecraft tells me that I am missing Baubles and to either delete Botania, or Get the mod, if you could provide a link to the correct mod, or help in any way, i'd appreciate it, Thanks!

**Comment by pahimar** [comment]
I think you have the wrong repo

**Comment by Gengi0927** [comment]
How do I fix this?

**Comment by nabijaczleweli** [comment]
Properly

**Comment by pahimar** [comment]
You report your issue to the Botania repository. Not to the Equivalent
Exchange repository.

On Oct 13, 2016 6:09 PM, "Jędrzej" <notifications@github.com> wrote:

Properly

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pahimar/Equivalent-Exchange-3/issues/1116#issuecomment-253653486>,
or mute the thread

**Comment by Gengi0927** [comment]
Oh, sorry, i thought i did. Thanks for letting me know! 'Facepalm'
