### ISSUE TITLE
Very minor issue

### ISSUE THREAD

**Issue by Keltas** [pahimar/Equivalent-Exchange-3#808]
Transmutation tablet can't be placed vertically. If I think about it, it makes sense, as everything would fall off, however vertical tablet would look cool. Also it seems to be impossible to place two arrays when their fragments are in the same block space as seen in the picture. I am no expert, but I think that means that arrays don't work with Forge multipart. Would it be possible to make them share the same area so that we can have more options to decorate our homes with totally safe circles with symbols that definitely will not blow us up?

![2015-05-04_21 40 46](https://cloud.githubusercontent.com/assets/6074403/7459685/689c8190-f2a6-11e4-8f0b-532d80293299.png)

**Comment by JAWSAWN** [comment]
power of the magic would stick the items on the board :P 
I'm pretty sure Pahimar is working on this.

**Comment by KlutzLament** [comment]
+1 I was thinking about making the exact same issue, but you beat me to it!

**Comment by pahimar** [comment]
I may look into vertical transmutation tablets, but with regards to arrays that "butt up" adjust each other I won't be adding that support because it gets very complicated for the dummy blocks to be aware of which array you are trying to use when you click on them (if they are associated with multiple arrays)
