### ISSUE TITLE
Bonemeal + Tall flower = infinite EMC

### ISSUE THREAD

**Issue by Chefbarbie** [pahimar/Equivalent-Exchange-3#837]
Flowers (lilac, rose bush, peony, sunflower) are 32EMC, bonemeal is 16. One bonemeal  = one tall flower with out losing the original.

**Comment by CatDany** [comment]
It's EE3, what do you want? ヽ(◉◡◔)ﾉ

**Comment by Tora-B** [comment]
That suggests that Flowers and bonemeal should have the same EMC value. However, using bonemeal on grass (the block, not tallgrass) can produce multiple small flowers, each worth 16 EMC. It's random, so I'm not sure what the enchange rate would be, but that's another infinite EMC exploit. I guess those kind of world interactions aren't taken into consideration by DynEMC. I imagine the current values were just pulled from EE2, when some of those interactions didn't exist, so those numbers will have to be reevaluated.

**Comment by Carbon-Ghost** [comment]
I don't consider this as an exploit personally, for me every EMC loops that are plants or water related aren't really "loops" as plants "regrow without end like trees even the tall flowers" and water is infinite cause F*** physics and E=MC^2 :D

**Comment by Tora-B** [comment]
I just built a device that could trivially automate this -- all it's lacking is the ability to automatically transmute the flowers into more bonemeal. Fully automatic 8 EMC per redstone tick, with just cheap vanilla components + EE3. That's a diamond every 103 seconds.
![2015-08-22_06 37 31](https://cloud.githubusercontent.com/assets/11331588/9423999/c4f8da5e-4898-11e5-8f43-1324d5c7d63b.png)

I'm sure it's possible to do something similar with trees, though you couldn't fully automate it with just vanilla. It would still probably be net EMC positive with the necessary automation, though probably not as fast as the tall flower method.

Tall flowers are trivially easy to fix: adjust the EMC values of tall flowers, bonemeal, or both, so that they're equal. Small flowers and tallgrass are a little harder because it produces a random amount, but it should be possible to get it close for the average case. Trees are harder still, for similar reasons. Four jungle saplings and 5-10 bonemeal produces a lot of wood, leaves, and vines.

**Comment by pahimar** [comment]
It's always going to be possible to automate "farms" to generate positive EMC gains. Hopefully in the future a yet-to-be-implemented "cost" system will help trim the gains (a configurable amount) to tune just how profitable these systems are.

In the meantime, classic EE abuse mechanic still going strong :-p
