### ISSUE TITLE
Smelted items doesn't get an EMC value

### ISSUE THREAD

**Issue by zlepper** [pahimar/Equivalent-Exchange-3#888]
When smelting items in a furnace the smeltet items doesn't have an EMC value.
Example:
   Grout from TCon has an emc value of 34.5, however Seared Bricks, which you get from smelting grout doesn't have an EMC value.

**Comment by reapersremorse** [comment]
It does that because there are multiple ways to make seared bricks. You can
use the smeltery with cobblestone melted in it to smelt into seared bricks,
if there is an unknown way to make an item or block with any mods then
dynamic MC will not figure up the EMC value. But since you know what the
bricks would cost you can use one of the commands added by Papa more to a
Danny McValue to any block or item as well as taking away and she values
excetera.

**Comment by reapersremorse** [comment]
Sorry .y speach to text is weird.

**Comment by zlepper** [comment]
There is also the hardened clay bucket from Inguana Tweaks, the clay bucket itself has an emc value equal to 3 pieces of clay, but the hardened bucket doesn't have an emc value.

-----Original Message-----

**Comment by reapersremorse** [comment]
I wonder if the recipe was added the same way as other smelting recipes. If
it was added to the list of furnace smelting items in a way that is
fifferent than vanilla, that could cause the dynamic emc system to not add
a value

**Comment by zlepper** [comment]
http://www.minecraftforge.net/wiki/Crafting_and_Smelting#1.7
https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/706dddd8e1603cb2cf118770a04879102abb93af/src/main/java/iguanaman/iguanatweakstconstruct/claybuckets/IguanaItems.java#L80
I think it's done correctly. 
However it might be an issue with recipes added later in the init process, point 3 here: https://github.com/pahimar/Equivalent-Exchange-3/issues/783

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
