### ISSUE TITLE
[Bug] Ticking block entity crash

### ISSUE THREAD

**Issue by Sirius902** [pahimar/Equivalent-Exchange-3#911]
When I try to open a server I made with EE3 it suddenly stopped working after using EE3 in the game, then closing. Previously, I was able to open the server but it stopped working now.

-Crash Report
http://pastebin.com/36bvQDuM

**Comment by Robijnvogel** [comment]
I know this is not the Research Station but the Calcinator, but I have a hunch it may be the same issue:
http://pastebin.com/RQpCbs4E

Info:
Since EE3 was updated on our server (after which I placed the Calcinator), the server has restarted several times without problems, but when we restarted it today, it crashed with this log within half an hour. It has at all times been chunkloaded, which means that the Calcinator has been "active" for over a week now.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
