### ISSUE TITLE
Setting EMC Value as 0 errors

### ISSUE THREAD

**Issue by MrPotatoGaming** [pahimar/Equivalent-Exchange-3#926]
EE3 version 507, forge version 1448

When using the commands "/ee3 set-energy-value-current-item <post/pre> 0" and "/ee3 set-energy-value <post/pre> <item> 0" the console tells me I am using the command parameters incorrectly. However, if I put the value below the console states that "the value must be at least 0.0" and setting the value as 0.1 works fine. Even setting the value to 1e-15 works. However, minecraft crashes when the later is transmuted too many times. 

Changing the value in the "post-assigned-energy-values.json" to 0 seems to work, but it says "emc value: 0" instead of "the item has no value" in the tooltip.  Which makes them free and not disabled.

**Comment by reapersremorse** [comment]
There is a command that strips emc from items. And one that makes them not
researchable

**Comment by MrPotatoGaming** [comment]
I saw the command that made the item not research able, but I didnt see the
command that strips it of emc. Does it not show up with tab complete? And
could you give me the command please?

**Comment by kcfc** [comment]
You can use `/ee3 set-item-not-learnable` to prevent an item from getting learned, ie. you won't be able to craft it with the transmutation tablet.

There is also `/ee3 set-item-not-recoverable` which disallows an item from being inputted into the transmutation tablet for energy. Unfortunately, this setting does not work in version 507. It was fixed in a6b06b50ae4239079f21c909daaca7b7cb8e4156

**Comment by MrPotatoGaming** [comment]
Ah thank you!

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
