### ISSUE TITLE
Running 0.3.0 on server times out or insta-disconnects you then crashes your game

### ISSUE THREAD

**Issue by DoughnutDev** [pahimar/Equivalent-Exchange-3#933]
Topic says it all but here is the log http://pastebin.com/zjNc8JCG

**Comment by DoughnutDev** [comment]
Also another thing EMC isnt working at all I have the new ExtraUtils and AE2EE3Compact and the other day there had EMC and the today there is no EMC at all. I tried deleting the world/data/ee3 stuff I tried /ee3 sync thing nothing. I don't know if this is EE3 or the other mods but they were working. I am going to try installing EE3Helper and run /ee3h regen to run the dynamic emc handler again and see if it regens them.

**Comment by bsaksida** [comment]
Regarding EMC issue. The problem lies, because of ExtraUtils. For example: Compressed cobblestone requires 9 cobblestone. ExtraUtil has a colored cobblestone and uses ore dictionary to handle recepies. And EE3 ignores ore dictionary in dynamicEMC generation.
Use EE3Helper and add missing emc to a recepies and then use regen command.

**Comment by DoughnutDev** [comment]
Why doesnt the AE2EE3Compact work anymore then?

**Comment by bsaksida** [comment]
I do not know. I personaly do not have any issue with AE2 EE3 EMC addon. The only issue is that one processor lacks EMC. I think it was enginering. Solved issue with EE3 Helper.

PS: Does it have to be EE3 0.3.0? The most Current on a curse client is 0.3.507. Maybe the issue was fixed and may solve your crashes

**Comment by DoughnutDev** [comment]
Well even on 0.3.507 I dont have EMC, but I tried 0.3.0 and it didn't work
on my server at all.

**Comment by DoughnutDev** [comment]
@bsaksida what command did you use to add the cobblestone?

**Comment by bsaksida** [comment]
Does AE2 have EMC when using EE3 v 0.3.507? For other missing emc, you will need to add yourself. Preferably using EE3 Helper mod. DynamicEMC is not perfect. Assign your self or wait until EE3 gets ore dictionary support. I suggest using EE3 helper

So you tried 0.3.507 and didn't work. Are you refering EMC assigment or a servers-timeout/disconnections. Based on your last comment, i could think that there is a version miss-mached betwen server-client.

If you think that EMC will get properly assigned on version 0.3.0, then you are out of luck. You can either remove ExtraUtilities. It adds a lot of colored cobblestone. Since its in ore dictionary, ee3 skips. Same can be said for Forestry. It adds toons of trees

**Comment by bsaksida** [comment]
If you want to use EE3 Helper add on, then for example you want to have all compressed cobblestone have emc.

Craft a single Compressed cobblestone (Since recepie uses ore dictionary EE3 skips assigment)
Have in a hotbar and have it sellected.
/ee3h add-item 1 (It will add emc of 1 to a currently selected item)
/ee3h regen (This will delete ee3 emc files and regenerate. You do not need to restart client/server)

**Comment by DoughnutDev** [comment]
I am using 507 and AE2 has no EMC at all even with the AE2EE3Comapact
installed

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
