### ISSUE TITLE
(New configuration setting) Balancing with experience

### ISSUE THREAD

**Issue by BurningEagle** [pahimar/Equivalent-Exchange-3#958]
EE3 can be seen as a very OP mod once a player finds a way of easy access to EMC. An example is compressed cobblestone, a technique used by Soaryn. 

For the people who agree with the above statement it would be nice to have a configuration setting that  makes the mod more balanced for those who want to. Currenty, once you have access to a lot of EMC, a player creates pretty much everything that he/she needs without really thinking about it, there a no consequences. By adding a new feature, this could change. The change I have in mind is that a player needs to use experience levels when converting EMC to items. The amount of XP required could be based of the amount of EMC used for crafting an item. 
This way people will think about what resources they really need and what they could gather in a different way, not blindly creating everything with it. Of course people would also find a way to gain Experience in a quick way but this is more end game and requires a lot more effort.

**Comment by MrPotatoGaming** [comment]
The point of EE3 is to have an equivalent exchange value. The reason problems like mass-produced cobblestone is an issue is because EE3 is built more around base game than heavily modded games. Because of which, getting millions of cobblestone a second isn't really plausible in vanilla. With that being said, Pahimar has plans to allow players to customize values of objects on a mod pack scale. This'll allow you to re balance EE3 if need be.

**Comment by BurningEagle** [comment]
it wouldn't remove the Equivalent exchange value, it would simply also imply an experience cost when converting EMC to an item. The point of EE3 would still be there.

**Comment by Wulfson** [comment]
Also suggested in #936

**Comment by pahimar** [comment]
For now the transmutation mechanic is how I'd like it to be, but I might open up more possibilities for it in the future. Closing.
