### ISSUE TITLE
...\world\playerdata\ee3\knowledge\transmutation\<playerhash>.json is reset to blank when leaving server.

### ISSUE THREAD

**Issue by aionys** [pahimar/Equivalent-Exchange-3#961]
Not sure if it also happens in single player, doesn't seem to, but whenever I log out of my server, the entire contents of my known transmutations file is replaced with the default:
"
{
    "canTransmuteEverything": false,
    "knownTransmutations": []
}
"

If I log back in and learn a new item, the file is refilled with all the knowledge I've done, which allows me to make a backup, but if the server is restarted with the file in the blank state above, all the knowledge is lost, and the transmutation tablet shows nothing, regardless of the current EMC amount.

As a side note, this only happens if I actually log out of the server- if I close Minecraft without logging out first, such as by clicking on the close window button or killing the java process, this issue does not occur.

**Comment by bluemoon1993** [comment]
Seconded

**Comment by driztin** [comment]
I am having this same issue on my server. but i did a little more digging into the behavior. 
When learning new transmutes the json file is not updated (not sure it expected behavior)
but when logging out of the server there is a write performed to the players .json file but there is nothing written to it. 

contents of the (player GUID).json file before and after logg out is the same. 

{
    "knownTransmutations": []
}

**Comment by lokilore** [comment]
Have the same issue here version EE3 Build 507, FTB Horizons II Daybreaker.
Single player the knowledge saves fine.
Multiplayer It does not save.
Oddly enough I copied my Single player .json file to the server and everything I added in single player stays although I cannot add anything new.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
