### ISSUE TITLE
random crash on server

### ISSUE THREAD

**Issue by Eidelmaim** [pahimar/Equivalent-Exchange-3#998]
for a few days now we have been seeing random crashes on our server and the crash report is pointing at ee3. was wondering if you could have a look and see if this issue is with ee3 or if something else is causing ee3 to generate this crash. thanks.

http://pastebin.com/mNm6u8fi

**Comment by Entoarox** [comment]
This is guaranteed to happen when removing an item with nill EMC from the tablet or rarely when shift-clicking.
The nill EMC issue happens rarely with items where the EMC does not get assigned properly for reasons unknown, resulting in the tablet version identifying as having a 0 EMC value but still showing up in the tablet because the actual item does have a proper EMC value.

**Comment by pahimar** [comment]
@entoarox you are mostly wrong. This is shift clicking. Items with no emc are not transmutable and not available as an option in the tablet.

**Comment by Entoarox** [comment]
@pahimar The item itself has EMC, it is just that the version shown in the tablet has no EMC and this causes a crash (the item in question was an enderIO resonant capacitor bank)

**Comment by pahimar** [comment]
If you see 0 emc in the tablet you have a sync issue thats affecting what is displayed. There is no "version of an item that has emc but also 0 emc". Read the code and stop theorizing

**Comment by Entoarox** [comment]
Please see https://dl.dropboxusercontent.com/u/14002006/2015-09-11_11.35.54.png
I was mistaken in the block causing the issue, since it was an AE energy cell and not the EnderIO resonant one, but the basic issue is still there. I have since removed the EMC value from the item to prevent others from crashing my server by causing this to happen, but as you can see there is clear proof that a item without EMC is showing up in the tablet after I used the research station to learn a version that did have EMC.

**Comment by Wulfson** [comment]
@Entoarox I seem to recall you talking about compiling custom versions of EE3...is the issue you're describing in one of those custom jars, or a proper released one?

**Comment by Entoarox** [comment]
@Wulfson The screenshot was on custom, but it is reproducable with the latest official version, I checked so that if it was an issue caused by the changes to dynEMC that the custom build makes, the author of the commit could fix it.

**Comment by pahimar** [comment]
If you are going to report issues in this Github, please only be reporting issues using builds that only come from this repo. If you are running custom builds, report issues to the creator of the custom build.

I cannot support other people's code.

Also, if you are going to report bugs, post steps to reproduce the bug.

**Comment by Eidelmaim** [comment]
Mr Pahimar, i appoligize for not including the steps to reproduce the issue, i my self am not very familiar with EE3, it was one of my players on the server who has been causeing this very crash... i will get with said individual and record him doing it and as well will take steps to reproduce it on my own and will also record that as well. as far as the version of EE3 we are using, it is a release that came with the Horizons: Daybreaker 1.1.0 FTB pack, EE3 version: 1.7.10-0.3.507

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
